name: couchdb
version: 2.2.0
summary: Document based database
description: CouchDB is a database that completely embraces the web. Store your data with JSON documents. Access your documents and query your indexes with your web browser, via HTTP. Index, combine, and transform your documents with JavaScript. 
confinement: strict
grade: stable

apps:
    server:
        daemon: simple
        command: rel/bin/snap_run
        plugs: [network-bind, process-control]
    couchdb:
        command: rel/bin/snap_run
        plugs: [network-bind, mount-observe, browser-support]
parts:
    couchdb: 
        plugin: nil
        override-build: |
          cp -ra /opt/couchdb $SNAPCRAFT_PART_INSTALL/rel/
        stage:
            - rel
        prime:
            - rel

    snap-config:
        plugin: dump
        source: ./snap/
        organize:
            couchdb.ini: rel/etc/default.d/couchdb.ini
            snap_run: rel/bin/snap_run

    packages:
        plugin: nil
        stage-packages:
            - libicu55
            - libmozjs185-1.0
        filesets:
            exclusion:
              - "-usr/share/doc/*"
              - "-usr/share/man/*"
        prime:
            - "$exclusion"
